// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DomainExpansion(arg1) {
  return window['go']['controllers']['AllNoteController']['DomainExpansion'](arg1);
}

export function GetData(arg1) {
  return window['go']['controllers']['AllNoteController']['GetData'](arg1);
}

export function Greet(arg1) {
  return window['go']['controllers']['AllNoteController']['Greet'](arg1);
}

export function GreetNight(arg1) {
  return window['go']['controllers']['AllNoteController']['GreetNight'](arg1);
}

export function Startup(arg1) {
  return window['go']['controllers']['AllNoteController']['Startup'](arg1);
}
