// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {entities} from '../models';
import {controllers} from '../models';
import {context} from '../models';

export function DomainExpansion(arg1:string):Promise<string>;

export function GetData(arg1:entities.DataSourceRequest):Promise<controllers.DataSourceResponseDTO>;

export function Greet(arg1:string):Promise<string>;

export function GreetNight(arg1:string):Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;
